baseurl = "https://okazaki418.github.io/tech_blog"
languageCode = "ja-jp"
title = "サーバとかネットワークとかの備忘録"
theme = "m10c"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"

[params]
  author = "okazaki"
  description = "大学院生の勉強日記"
  menu_item_separator = " - "

  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/okazaki418"
